github_url: https://github.com/Polidea/RxBluetoothKit
module: RxBluetoothKit
module_name: RxBluetoothKit
author_url: https://polidea.com
author: Polidea
author_name: Polidea
swift_version: 2.2
clean: true
output: Documentation

podspec: RxBluetoothKit.podspec
